---
title: "Premiers calculs"
author: "Sébastien Guyader"
date: "24octobre 2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importer les données

Je commence par créer un vecteur avec les données :

```{r données}
my_data <- c(14.0, 7.6, 11.2, 12.8, 12.5, 9.9, 14.9, 9.4, 16.9, 10.2, 14.9, 18.1, 7.3, 9.8, 10.9, 12.2, 9.9, 2.9, 2.8, 15.4, 15.7, 9.7, 13.1, 13.2, 12.3, 11.7, 16.0, 12.4, 17.9, 12.2, 16.2, 18.7, 8.9, 11.9, 12.1, 14.6, 12.1, 4.7, 3.9, 16.9, 16.8, 11.3, 14.4, 15.7, 14.0, 13.6, 18.0, 13.6, 19.9, 13.7, 17.0, 20.5, 9.9, 12.5, 13.2, 16.1, 13.5, 6.3, 6.4, 17.6, 19.1, 12.8, 15.5, 16.3, 15.2, 14.6, 19.1, 14.4, 21.4, 15.1, 19.6, 21.7, 11.3, 15.0, 14.3, 16.8, 14.0, 6.8, 8.2, 19.9, 20.4, 14.6, 16.4, 18.7, 16.8, 15.8, 20.4, 15.8, 22.4, 16.2, 20.3, 23.4, 12.1, 15.5, 15.4, 18.4, 15.7, 10.2, 8.9, 21.0)
```

## Réaliser les calculs

Je crée des variables pour calcul demandé :

```{r}
moyenne <- mean(my_data) 
minimum <- min(my_data)
ecart_type <- sd(my_data)
mediane <- median(my_data)
maximum <- max(my_data)
```

## Affichage des valeurs

Je crée un dataframe avec les valeurs calculées arrondies à 2 décimales, puis je l'affiche :

```{r}
df <- data.frame(round(moyenne,2),round(minimum,2),round(ecart_type,2),round(mediane,2),round(maximum,2))
colnames(df) <- c("Moyenne", "Minimum", "Ecart-type", "Médiane", "Maximum")
df
```

