---
title: "Séminaires Astro - Préparation Evaluation"
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 3
    toc_float: true
    df_print: kable
  pdf_document:
    toc: true
    toc_depth: 2
    df_print: kable
    latex_engine: xelatex
mainfont: Avenir Next LT Pro
fontsize: 18pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 2019-12-11

## Discussions sur les 4 thèmes transversaux identifiés en CODIR

- rappel des 4 thèmes :
  * Gestion de l'agrodiversité pour une gestion durable du milieu et des bioagresseurs
  * Transition de l’agriculture vers des écosystèmes de micro-fermes
  * Changement climatique, vulnérabilités de l’agriculture, quelles perspectives pour l’unité ?
  * Agriculture sur sols pollués : quelle place dans le projet d’unité ?
- autre thème éventuel à dicuter : "Sciences et politiques publiques"
- éclaircir et prendre en compte la notion de changement/intégration d'échelle(s), notion d'amplification des échelles basales vers supérieures
- pour les discussions à venir, se ménager un temps pour discuter des liens entre les thèmes
- comment les microfermes peuvent contribuer aux expérimentations analytiques ?


### 1. "Gestion de la diversité / agrosystèmes / gestion durable du milieu et des bioagresseurs"

**Tour de table :**

- FC : y voit le changement vers moins de monocultures, moins de spécialisation dans les exploitations sur l'une des 2 cultures d'exportation ; associations doivent aller vers plusieurs cultures de rente ensemble, pas seulement 1 de rente et d'autres de service
- AR : y voit question du biocontrôle, restauration du milieu ou culture sur sols pollués
- TB : agroécologie, diversité des pratiques, cultures et techniques
- DP : 2 aspects, utilisation de la biodiversité, et aussi générer de la diversité
- LP : penser les idéotypes capables de bien se comporter en mélange interspécifique
- YF : désherbage sélectif
- MC : intégrer les micro- et macroorganismes associés
- MU : impact positif des sols couverts
- AR : intégration possible de l'agroforesterie, polyculture-élevage ?
- RT : retirer le terme "agro" pour juste "écologie"
- SG : cultiver c'est pas seulement planter, c'est aussi gérer/favoriser d'autres organismes ("adventices", microbes) ; penser aussi à comment transposer les résultats du type "quoi cultiver, où et quand" vers les acteurs : aide à la décision, politiques publiques

**Collaborations**

- Brésil (LP)
- Côte d'Ivoire, BGPI/BFP INRAE/CIRAD, Suzane Seal NRI (MU)
- Instituts Techniques, profession, DAAF...

### 2. "Transition vers des écosystèmes de microfermes"

**Idées pêle-mêle :**

- comment définit-on une microferme ? (TB) : en général, moins de 2 ha (JMB)
- transition :
  * concerne les espèces ? les pratiques ? les fonctions (production, transformation, fonction sociale, services écosystémiques)
  * repenser l'organisation du système agricole ?
- besoin de transition dans la formation agricole aussi
- repenser les partenariats locaux
- microferme : on peut y faire ce qu'on veut a priori, mais souvent c'est du maraîchage

**Initiative PIA**

- demande issue de le DG
- deadline repoussée à janvier
- soutien d'INRA Transfert, appui demandé à l'ADEME au niveau national, en bonne voie
- la SAFER portera le projet en Guadeloupe
- concept :
  * transition de modèle agricole en Guadeloupe
  * prise de conscience de l'aspect impact (environnement, santé)
  * beaucoup de demandes de jeunes, plutôt pour de petites surface
  * aller vers davantage d'autonomie alimentaire
  * donc moins intensifer, diversifier
  * besoin de fournir des biointrants d'origine locale, des pistes existent
  * besoin de faire de la formation (initiale, et accompagnement)
  * explorer l'application du numérique
  * comment bien vendre/commercialiser : mutualisation -> notion d'écosystème de microfermes
  * besoin d'agrotransformation
  * volet énergie (y-compris production sur place)
  * volet formation
  * ingénierie financière (chiffrage approximatif à 300k€ par microferme pour l'installation)
  * volet habitation
  * il y aurait un processus de sélection des candidats pour le démonstrateur industriel
  * 4 systèmes de 4 microfermes (Nord-GT, Nord-BT, Sud-BT, Marie-Galante)
  * intérêt à coupler cela au tourisme
- la région est prête à soutenir y-compris après la mise en place
- discussions :
  * intégration de pépinières
  * intégrer les consommateurs via la publicité pour les inciter à se tourner vers lesproduits de ces microfermes
  * vigilence sur le fait de ne pas aller vers une agriculture trop élitiste
  * l'INRA peut jouer un rôle d'hôte pour la formation, et de formateur de formateurs
  
### 3. "Agriculture et sols pollués"

**Introduction A. Richard**

- ce qui a été fait :
  * travaux sur transferts pollutions sol vers plantes et animaux
  * comportement de la chlordécone dans différents types de sols (modèle biophysique)
  * cartographie zones à risques associée à préconisations de types de cultures
  * observatoire pour suivre chlordécone et autres pesticides
- ce qui est en cours :
  * travaux Astro/Lysah *via* réseau Opale : compréhension mécanismes de transfert à l'échelle du bassin versant et échelles détail sur échelles inférieures (Lise) et composantes du sol (Antoine)
  * sécurisation des productions sur sols pollués (limiter transferts sols/plantes)
  * période de décontamination des animaux pour descendre en dessous des seuils
  * va démarrer : usage de charbons actifs pour limiter les transferts
- propositions points d'entrée :
  *a.* gestion de la contamination
  *b.* aller vers la dépollution ?
  *c.* poursuite des travaux sur la compréhension des mécanismes de transferts
  *d.* sciences humaines et sociales ?
  *e.* lien avec autres axes de recherche
  