graph TD
    linkStyle default interpolate bundle
    EUMYCOTA --> Chytridiomycota
    EUMYCOTA --> invisible1
    Chytridiomycota --> Chytridiomycètes
    invisible1 --> Mucoromycètes
    invisible1 --> Symbiomycota
    Symbiomycota --> Gloméromycètes
    Symbiomycota --> Dikarya
    Dikarya --> Entorrhizomycètes
    Dikarya --> Basidiomycètes
    Dikarya --> Ascomycètes
    Chytridiomycota --> invisible1

#linkStyle default interpolate linear